description: expect the unexpected through better strategic planning
typography_spectrum: 0.5391724817454815
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
author:
  name: Tom Boudreau
  email: tomboudreauwi@gmail.com
layout_spectrum: 0.4510638
title: WI Risk Management
color:
  saturation: 0.6659575
  brandStrength: 0.3259262915235013
  rhythmicContrast: 0.7319149
  brandColors:
    - '#FFFFFF'
    - '#232F3E'
    - '#BABABA'
    - '#959595'
    - '#6A6A6A'
  lightness: 0.5042553
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/36d6fd67-7758-4d51-b2e0-f5fc29435a9b.jpg
favicon: null
content_rating:
  adult: false
analytics:
  twitter: boudreau_tom
name: "Tom Boudreau \_ \_262-446-5420"
