title: wi risk management
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: expect the unexpected through better strategic planning
color:
  saturation: 0.6659575
  brandStrength: 0.3259262915235013
  lightness: 0.5042553
  brandColors:
    - '#FFFFFF'
    - '#232F3E'
    - '#BABABA'
    - '#959595'
    - '#6A6A6A'
  rhythmicContrast: 0.7319149
favicon: null
author:
  name: Tom Boudreau
  email: tomboudreauwi@gmail.com
name: tomboudreau
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/36d6fd67-7758-4d51-b2e0-f5fc29435a9b.jpg
typography_spectrum: 0.5391724817454815
layout_spectrum: 0.3752313232980669
content_rating:
  adult: false
