typography_spectrum: 0.5391724817454815
content_rating:
  adult: false
color:
  saturation: 0.6659575
  brandStrength: 0.3259262915235013
  rhythmicContrast: 0.7319149
  brandColors:
    - '#FFFFFF'
    - '#232F3E'
    - '#BABABA'
    - '#959595'
    - '#6A6A6A'
  lightness: 0.5042553
layout_spectrum: 0.4510638
analytics:
  twitter: boudreau_tom
  google: UA-83330140-1
author:
  name: Tom Boudreau
  email: tomboudreauwi@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/36d6fd67-7758-4d51-b2e0-f5fc29435a9b.jpg
name: "Tom Boudreau \_ \_262-446-5420"
navigation:
  - name: LinkedIn Profile
    url: 'https://www.linkedin.com/in/tomboudreau'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: WI Risk Management
description: expect the unexpected through better strategic planning
