typography_spectrum: 0.5391724817454815
content_rating:
  adult: false
color:
  brandStrength: 0.3259262915235013
  lightness: 0.35027124057523906
  saturation: 0.37668885197490454
  rhythmicContrast: 0.6091220921371132
  brandColors:
    - '#FFFFFF'
    - '#0E361C'
    - '#6A8675'
    - '#199955'
    - '#C4DCCC'
layout_spectrum: 0.37523132329806685
author:
  name: Tom Boudreau
  email: tomboudreauwi@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/36d6fd67-7758-4d51-b2e0-f5fc29435a9b.jpg
name: tomboudreau
favicon: null
title: wi risk management
description: expect the unexpected through better strategic planning
