title: wi risk management
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: expect the unexpected through better strategic planning
color:
  saturation: 0.7404255
  brandStrength: 0.3259262915235013
  lightness: 0.6723405
  brandColors:
    - '#151412'
    - '#00FFC3'
    - '#26542E'
    - '#B69F97'
    - '#02CA76'
  rhythmicContrast: 0.7319149
favicon: null
name: tomboudreau
author:
  name: Tom Boudreau
  email: tomboudreauwi@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/36d6fd67-7758-4d51-b2e0-f5fc29435a9b.jpg
typography_spectrum: 0.5391724817454815
layout_spectrum: 0.3752313232980669
content_rating:
  adult: false
